name: meetup
description: A new Flutter project.

version: 1.0.0+10

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  flutter_datetime_picker_plus: ^2.0.1
  flutter_screenutil: ^5.8.4
  get_it: ^7.6.0
  google_fonts: 6.1.0
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  logger: 2.0.2+1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  provider: ^6.0.5
  share_plus: ^7.1.0
  shimmer: ^3.0.0
  timeago: ^3.5.0
  url_launcher: ^6.1.11

flutter_gen:
  output: lib/

dev_dependencies:
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#FFFFFF"
  android: true
  ios: true
  web: true
  fullscreen: false
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#D8F3DF"
  ios: true
  image_path_ios: "assets/images/logo.png"
  image_path: "assets/images/logo.png"

# flutter pub run flutter_launcher_icons
# dart run flutter_native_splash:create
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
